# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('type', models.CharField(choices=[('Pub', 'Pub'), ('Coffee', 'Coffee'), ('Disco', 'Disco')], max_length=30, verbose_name='Type')),
                ('openingTime', models.IntegerField(verbose_name='Opening time')),
                ('closingTime', models.IntegerField(verbose_name='Closing time')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('date', models.DateField(verbose_name='Date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kindergarten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('min_age', models.IntegerField(verbose_name='Minimum age')),
                ('max_age', models.IntegerField(verbose_name='Maximum age')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('qualification', models.IntegerField(verbose_name='Qualification')),
                ('openingTime', models.IntegerField(verbose_name='Opening time')),
                ('closingTime', models.IntegerField(verbose_name='Closing time')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('goods', models.CharField(max_length=100, verbose_name='Goods')),
                ('openingTime', models.IntegerField(verbose_name='Opening time')),
                ('closingTime', models.IntegerField(verbose_name='Closing time')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
